/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__CONF_H__)
#define __CONF_H__


/* the default :-separated search path */
#if !defined(DEFAULTCALCPATH)
#define DEFAULTCALCPATH "./cal"
#endif /* DEFAULTCALCPATH */

/* the default :-separated startup file list */
#if !defined(DEFAULTCALCRC)
#define DEFAULTCALCRC "/lib/calc/startup:~/.calcrc:./.calcinit"
#endif /* DEFAULTCALCRC */

/* the location of the help directory */
#if !defined(HELPDIR)
#define HELPDIR "/lib/calc/help"
#endif /* HELPDIR */

/* the location of the custom help directory */
#if !defined(CUSTOMHELPDIR)
#define CUSTOMHELPDIR "/lib/calc/help/custhelp"
#endif /* CUSTOMHELPDIR */

/* the default pager to use */
#if !defined(DEFAULTCALCPAGER)
#define DEFAULTCALCPAGER "less.exe"
#endif /* DEFAULTCALCPAGER */


#endif /* !__CONF_H__ */
