/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__ENDIAN_CALC_H__)
#define __ENDIAN_CALC_H__


/* what byte order are we? */
#define BIG_ENDIAN	4321
#define LITTLE_ENDIAN	1234
#define CALC_BYTE_ORDER	LITTLE_ENDIAN


#endif /* !__ENDIAN_CALC_H__ */
