/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_GETPGID_H)
#define CALC_HAVE_GETPGID_H


/* do we have or want getpgid()? */
#undef HAVE_GETPGID /* no */


#endif /* !CALC_HAVE_GETPGID_H */
