/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__HAVE_UNISTD_H__)
#define __HAVE_UNISTD_H__


/* do we have <unistd.h>? */
#undef HAVE_UNISTD_H  /* no */


#endif /* !__HAVE_UNISTD_H__ */
