/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_UNISTD_H)
#define CALC_HAVE_UNISTD_H


/* do we have <unistd.h>? */
#undef HAVE_UNISTD_H  /* no */


#endif /* !CALC_HAVE_UNISTD_H */
