/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__HAVE_STRDUP_H__)
#define __HAVE_STRDUP_H__


/* do we have or want getstrdup()? */
#define HAVE_STRDUP /* yes */


#endif /* !__HAVE_STRDUP_H__ */
