/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_RUSAGE_H)
#define CALC_HAVE_RUSAGE_H


/* do we have or want getrusage()? */
#undef HAVE_GETRUSAGE /* no */


#endif /* !CALC_HAVE_RUSAGE_H */
