/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__HAVE_URANDOM_H__)
#define __HAVE_URANDOM_H__


/* do we have /dev/urandom? */
#undef HAVE_URANDOM_H  /* no */


#endif /* !__HAVE_URANDOM_H__ */
