/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_FPOS_H)
#define CALC_HAVE_FPOS_H


/* do we have fgetpos & fsetpos functions? */
#undef HAVE_FPOS  /* no */

typedef long FILEPOS;


#endif /* !CALC_HAVE_FPOS_H */
