/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__HAVE_STRING_H__)
#define __HAVE_STRING_H__


/* do we have <string.h>? */
#define HAVE_STRING_H	/* yes */


#endif /* !__HAVE_STRING_H__ */
