/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__HAVE_UNUSED_H__)
#define __HAVE_UNUSED_H__


/* do we have/want the unused attribute? */
#define HAVE_UNUSED /* yes */
#undef UNUSED
#define UNUSED __attribute__((unused)) /* yes */


#endif /* !__HAVE_UNUSED_H__ */
