/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__LONGBITS_H__)
#define __LONGBITS_H__


#undef LONG_BITS
#define LONG_BITS 32		/* bit length of a long */

/* size of long was forced */

typedef unsigned char USB8;	/* unsigned 8 bits */
typedef signed char SB8;	/* signed 8 bits */

typedef unsigned short USB16;	/* unsigned 16 bits */
typedef short SB16;		/* signed 16 bits */

typedef unsigned long USB32;	/* unsigned 32 bits */
typedef long SB32;		/* signed 32 bits */

#undef HAVE_B64			/* we have no USB64 and no SB64 types */

/* no 64 bit constants */
#define U(x) no 33 to 64 bit constants - do not use this macro!
#define L(x) no 33 to 64 bit constants - do not use this macro!


#endif /* !__LONGBITS_H__ */
