/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__LONGLONG_H__)
#define __LONGLONG_H__


/* do we have/want to use a long long type? */
#undef HAVE_LONGLONG
#define LONGLONG_BITS 0  /* no */
#undef L64_FORMAT


#endif /* !__LONGLONG_H__ */
